# Site Information
site_name: "WNDI"
site_description: "Mark Huang's Personal Documentation"
site_author: Mark Huang
docs_dir: docs/

# GitHub repository button (shown at the top-right corner)
# repo_name: 'MarkHershey/docs'
# repo_url: 'https://github.com/MarkHershey/docs'

# Copyright Declaration (shown at the end of the page)
copyright: "Mark Huang &copy; 2019-2022. All Rights Reserved."

# Footer Customization
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/MarkHershey
        - icon: fontawesome/solid/home
          link: https://markhh.com/
    analytics:
        provider: google
        property: G-HV3ZHE7B6V

# Extensions
# https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
markdown_extensions:
    - attr_list # https://squidfunk.github.io/mkdocs-material/reference/buttons/#attribute-list
    - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition
    - pymdownx.caret # handling sub- and superscripts
    - pymdownx.mark # highlighting of text
    - pymdownx.tilde # strikethrough of text
    - pymdownx.keys # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#keys
    - pymdownx.details # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#details
    - pymdownx.highlight # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
    - pymdownx.smartsymbols # supporting special characters like copyright symbol (c)
    - pymdownx.superfences # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#superfences
    - pymdownx.tabbed: # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#tabbed
          alternate_style: true
    - pymdownx.arithmatex: # https://squidfunk.github.io/mkdocs-material/reference/mathjax/#arithmatex
          generic: true
    - pymdownx.emoji: # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#emoji
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tasklist: # https://squidfunk.github.io/mkdocs-material/reference/lists/#tasklist
          custom_checkbox: true
          clickable_checkbox: true
    - toc: # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#table-of-contents
          permalink: "#"

# Theme Configuration
theme:
    name: material
    favicon: img/memory-solid.svg # for browser tab icon
    logo: img/memory-solid.svg # for top-left site logo
    icon:
        # logo: fontawesome/solid/memory # for top-left site logo
        repo: fontawesome/brands/github # for top-right repo link only
    features:
        # - navigation.instant
        - navigation.tabs
        - navigation.expand
    palette:
        - scheme: default
          primary: teal
          accent: lime
          toggle:
              icon: material/lightbulb
              name: Switch to dark mode
        - scheme: slate
          primary: teal
          accent: lime
          toggle:
              icon: material/lightbulb-outline
              name: Switch to light mode

extra_javascript:
    - javascripts/config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Navigation menu
nav:
    - Home: "index.md"
    - Projects:
          - Dotfiles: "pages/project/dotfiles.md"
    - Dev References:
          - Dev Tools:
                - Docker: "pages/dev/docker.md"
                - VIM: "pages/dev/vim_ref.md"
                - Tmux: "pages/dev/tmux_ref.md"
                - Git: "pages/dev/git.md"
                - GPG: "pages/dev/gpg.md"
          - Networks:
                - Internet Protocols: "pages/networks/internet_protocols.md"
                - Network Layer: "pages/networks/network_layer.md"
                - Network Data Unit: "pages/networks/network_data_units.md"
                - DNS: "pages/networks/dns.md"
                - SSH: "pages/networks/ssh.md"
                - Inter-Process Comms: "pages/networks/ipc.md"
                - TLS Certificate: "pages/networks/tls_certificate.md"
                - NPS: "pages/networks/nps.md"
                - NGINX: "pages/networks/nginx.md"
          - Systems:
                - Linux Commands: "pages/dev/linux-commands.md"
                - Linux Distros: "pages/dev/linux-distros.md"
                - File Systems: "pages/dev/file_systems.md"
                - Mount G-Drive headlessly: "pages/dev/linux-mount-gdrive.md"
          - PL:
                - Python:
                      - Subprocess Call: "pages/python/subprocess_call.md"
                - LaTex: "pages/dev/latex_ref.md"
                - Java:
                      - Concurrency: "pages/lang/java/concurrency.md"
          - NVIDIA:
                - Install Driver on Ubuntu: "pages/dev/nvidia_driver.md"
                - NVIDIA-SMI Commands: "pages/dev/nvidia-smi.md"
    - Resources:
          - CS Books: "pages/cs/cs_books.md"
          - CS Online Courses: "pages/cs/cs_courses.md"
          - Tools:
                - Toolkit: "pages/tools/toolkit.md"
                - Static Site Generators: "pages/tools/static_site_generators.md"
                - MkDocs Material: "pages/tools/mkdocs_demo.md"
    - ML:
          - General:
                - Types of Machine Learning: "pages/ml/types_of_ml.md"
                - Blogs: "pages/ml/blogs.md"
                - SVM: "pages/ml/SVM.md"
                - KL Divergence vs Cross Entropy: "pages/ml/kl.md"
          - CV:
                - CNN Visualization: "pages/ml/cnn_visuals.md"
          - NLP:
                - Word Embedding: "pages/ml/word_embedding.md"
          - Code:
                - Matrix Ops - NumPy vs PyTorch: "pages/ml/numpy_torch_ops.md"
    - SUTD:
          - SUTD Bookmarks: "pages/sutd/bookmarks.md"
          - CS Education at SUTD:
                - CSD TERM 4: "pages/sutd/csd_term4.md"
                - CSD TERM 5: "pages/sutd/csd_term5.md"
                - CSD TERM 6: "pages/sutd/csd_term6.md"
                - CSD TERM 7: "pages/sutd/csd_term7.md"
    - MISC:
          - SEA: "pages/hass/SEA.md"
