# Site Information
site_name: "WNDI"
site_description: "Mark Huang's Personal Documentation"
site_author: Mark Huang
docs_dir: docs/

# GitHub repository button (shown at the top-right corner)
# repo_name: 'MarkHershey/docs'
# repo_url: 'https://github.com/MarkHershey/docs'

# Copyright Declaration (shown at the end of the page)
copyright: "Mark Huang &copy; 2019-2021. All Rights Reserved."

# Footer Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MarkHershey
    - icon: fontawesome/solid/asterisk
      link: https://markhh.com/
  analytics:
    provider: google
    property: G-HV3ZHE7B6V


# Extensions
# https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
markdown_extensions:
    - attr_list # https://squidfunk.github.io/mkdocs-material/reference/buttons/#attribute-list
    - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition
    - pymdownx.caret # handling sub- and superscripts
    - pymdownx.mark # highlighting of text
    - pymdownx.tilde # strikethrough of text
    - pymdownx.keys # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#keys
    - pymdownx.tabbed # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#tabbed
    - pymdownx.details # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#details
    - pymdownx.highlight # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
    - pymdownx.superfences # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#superfences
    - pymdownx.smartsymbols # supporting special characters like copyright symbol (c)
    - pymdownx.arithmatex: # https://squidfunk.github.io/mkdocs-material/reference/mathjax/#arithmatex
        generic: true
    - pymdownx.emoji: # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#emoji
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tasklist: # https://squidfunk.github.io/mkdocs-material/reference/lists/#tasklist
        custom_checkbox: true
        clickable_checkbox: true
    - toc: # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#table-of-contents
        permalink: "#"
  

# Theme Configuration
theme:
    name: material
    favicon: img/memory-solid.svg     # for browser tab icon
    icon:
      logo: fontawesome/solid/memory  # for top-left site logo
      repo: fontawesome/brands/github # for top-right repo link only
    features:
      # - navigation.instant
      - navigation.tabs
      - navigation.expand
    palette:
      - scheme: default
        primary: indigo
        accent: pink
        toggle:
          icon: material/lightbulb
          name: Switch to darker mode
      - scheme: slate
        # primary: teal
        primary: deep purple
        # accent: indigo
        accent: lime
        toggle:
          icon: material/lightbulb-outline
          name: Switch to lighter mode

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Navigation menu
nav:
    - Home: 'index.md'
    - Projects:
      - Dotfiles: 'pages/project/dotfiles.md'
    - Dev References:
      - Dev Tools:
        - Docker: 'pages/dev/docker.md'
        - VIM: 'pages/dev/vim_ref.md'
        - Tmux: 'pages/dev/tmux_ref.md'
        - Git: 'pages/dev/git.md'
      - Networking:
        - Inter-Process Comms: 'pages/dev/ipc.md'
        - Internet Protocols: 'pages/dev/internet_protocols.md'
        - DNS: 'pages/dev/dns.md'
        - SSH: 'pages/dev/ssh.md'
        - TLS Certificate: 'pages/dev/tls_certificate.md'
        - NPS: 'pages/dev/nps.md'
      - Linux:
        - Linux Commands: 'pages/dev/linux-commands.md'
        - Linux Distros: 'pages/dev/linux-distros.md'
        - Mount G-Drive headlessly : 'pages/dev/linux-mount-gdrive.md'
      - Languages:
        - LaTex: 'pages/dev/latex_ref.md'
        - Java:
          - Concurrency: 'pages/lang/java/concurrency.md'
      - NVIDIA:
        - Install Driver on Ubuntu: 'pages/dev/nvidia_driver.md'
        - NVIDIA-SMI Commands: 'pages/dev/nvidia-smi.md'
    - Resources:
      - CS Books: 'pages/cs/cs_books.md'
      - CS Online Courses: 'pages/cs/cs_courses.md'
      - CS Education at SUTD:
        - ISTD TERM 4: 'pages/cs/istd_term4.md'
        - ISTD TERM 5: 'pages/cs/istd_term5.md'
        - ISTD TERM 6: 'pages/cs/istd_term6.md'
      - Tools: 
        - Toolkit: 'pages/tools/toolkit.md'
        - Static Site Generators: 'pages/tools/static_site_generators.md'
        - MkDocs Material: 'pages/tools/mkdocs_demo.md'
    - ML:
      - CNN Visualization: 'pages/ml/cnn_visual.md'
    - SUTD:
      - SUTD Bookmarks: 'pages/sutd/bookmarks.md'
