# Site Information
site_name: "WNDI"
site_description: "Mark Huang's Personal Documentation"
site_author: Mark Huang
docs_dir: docs/

# GitHub repository button (shown at the top-right corner)
# repo_name: 'MarkHershey/docs'
# repo_url: 'https://github.com/MarkHershey/docs'

# Copyright Declaration (shown at the end of the page)
copyright: "Mark Huang &copy; 2019-2021. All Rights Reserved."

# Footer Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MarkHershey/docs


# Extensions
# https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
markdown_extensions:
    - attr_list # https://squidfunk.github.io/mkdocs-material/reference/buttons/#attribute-list
    - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition
    - pymdownx.caret # handling sub- and superscripts
    - pymdownx.mark # highlighting of text
    - pymdownx.tilde # strikethrough of text
    - pymdownx.keys # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#keys
    - pymdownx.tabbed # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#tabbed
    - pymdownx.details # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#details
    - pymdownx.highlight # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
    - pymdownx.superfences # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#superfences
    - pymdownx.smartsymbols # supporting special characters like copyright symbol (c)
    - pymdownx.arithmatex: # https://squidfunk.github.io/mkdocs-material/reference/mathjax/#arithmatex
        generic: true
    - pymdownx.emoji: # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#emoji
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tasklist: # https://squidfunk.github.io/mkdocs-material/reference/lists/#tasklist
        custom_checkbox: true
        clickable_checkbox: true
    - toc: # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#table-of-contents
        permalink: "#"
  

# Theme Configuration
theme:
    name: material
    favicon: img/memory-solid.svg     # for browser tab icon
    icon:
      logo: fontawesome/solid/memory  # for top-left site logo
      repo: fontawesome/brands/github # for top-right repo link only
    features:
      # - navigation.instant
      - navigation.tabs
      - navigation.expand
    palette:
        scheme: slate
        primary: lime
        accent: indigo

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Navigations
nav:
    - Home: 'index.md'
    - Projects:
      - Dotfiles: 'project/dotfiles.md'
    - Dev References:
      - Dev Tools:
        - Docker: 'dev/docker.md'
        - VIM: 'dev/vim_ref.md'
        - Tmux: 'dev/tmux_ref.md'
      - Networking:
        - DNS: 'dev/dns.md'
        - SSH: 'dev/ssh.md'
        - TLS Certificate: 'dev/tls_certificate.md'
      - Linux:
        - Linux Commands: 'dev/linux-commands.md'
        - Linux Distros: 'dev/linux-distros.md'
        - Mount G-Drive headlessly : 'dev/linux-mount-gdrive.md'
    - CS Resources:
      - CS Books: 'cs/cs_books.md'
      - CS Online Courses: 'cs/cs_courses.md'
      - CS Education at SUTD:
        - ISTD TERM 4: 'cs/istd_term4.md'
        - ISTD TERM 5: 'cs/istd_term5.md'
    - SUTD:
      - SUTD Bookmarks: 'SUTD/sutd_bookmarks.md'
