# Site Information
site_name: WNDI
site_description: Mark Huang's Personal Documentation
site_author: Mark Huang
docs_dir: docs/

# GitHub repository button (shown at the top-right corner)
# repo_name: 'MarkHershey/docs'
# repo_url: 'https://github.com/MarkHershey/docs'

# Copyright Declaration (shown at the end of the page)
copyright: Mark Huang &copy; 2019-2021. All rights reserved.

# Footer Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MarkHershey/docs


# Extensions
markdown_extensions:
    - attr_list
    - admonition
    - pymdownx.keys
    - pymdownx.tabbed
    - pymdownx.details
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - toc:
        permalink: "#"
  

# Theme Configuration
theme:
    name: material
    favicon: img/memory-solid.svg     # for browser tab icon
    icon:
      logo: fontawesome/solid/memory  # for top-left site logo
      repo: fontawesome/brands/github # for top-right repo link only
    features:
      # - navigation.instant
      - navigation.tabs
      - navigation.expand
    palette:
        scheme: slate
        primary: lime
        accent: indigo

extra_javascript:
  # - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Navigations
nav:
    - Home: 'index.md'
    - Dev References:
      - Docker: 'dev/docker.md'
      - SSH: 'dev/ssh.md'
      - VIM: 'dev/vim_ref.md'
      - Linux CLI: 'dev/linux-commands.md'
      - Linux Distros: 'dev/linux-distros.md'
      - Computer Science Stuff:
        - CS Books: 'cs/cs_books.md'
        - CS Education at SUTD:
          - ISTD TERM 4: 'cs/istd_term4.md'
          - ISTD TERM 5: 'cs/istd_term5.md'
    - SUTD:
      - SUTD Bookmarks: 'SUTD/sutd_bookmarks.md'
