# Site Information
site_name: Documentation
site_description: Mark Huang's Personal Documentation
site_author: Mark Huang
docs_dir: docs/

# GitHub repository button (shown at the top-right corner)
# repo_name: 'MarkHershey/docs'
# repo_url: 'https://github.com/MarkHershey/docs'

# Copyright Declaration (shown at the end of the page)
copyright: Mark Huang &copy; 2020. All rights reserved.

# Extensions
markdown_extensions:
    - toc:
        permalink: "#"
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.arithmatex:
        generic: true
        
# Theme Configuration
theme:
    name: material
    favicon: img/favicon.ico
    icon:
      logo: fontawesome/solid/toilet-paper
      # logo: img/favicon.svg
    features:
      - navigation.tabs
    palette:
        scheme: slate
        primary: lime
        accent: indigo
        
extra_javascript:
  # - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Navigations
nav:
    - Home: 'index.md'
    - Computer Science: 
      - main: 'cs.md'
